name: ğŸ³ Build and Push Docker images

run-name: ${{ github.head_ref || github.ref_name }}-docker-build-push

on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  # Reuse the build job from docker-build.yml
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

  # Add push job that depends on successful build
  docker-push:
    needs: docker-build
    name: "Push Docker Image"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 5
    permissions:
      actions: write
      checks: write
      contents: write
      packages: write

    steps:
      - name: ğŸ” Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}s

      - name: ğŸš€ Tag and Push to DockerHub
        run: |
          # Tag the images
          docker tag lsadf-api:latest ${{ github.GHCR_USERNAME }}/lsadf-api:latest
          docker tag lsadf-api:latest ${{ github.GHCR_USERNAME }}/lsadf-api:${{ github.sha }}
          
          # Push the images
          docker push ${{ github.GHCR_USERNAME }}/lsadf-api:latest
          docker push ${{ github.GHCR_USERNAME }}/lsadf-api:${{ github.sha }}
